@url_jugadores= http://localhost:8080/api/jugadores
@url_partidos= http://localhost:8080/api/partidos

###
GET {{url_jugadores}}

###
POST {{url_jugadores}}
Content-Type: application/json

{
    "nombre": "Paquito",
    "apellido": "Navarro",
    "telefono": 0,
    "posicion": "Drive",
    "nivel": 7,
    "ranking": 0,
    "fk_usuario": 1,
    "fk_partido": 1
}
###
PUT {{url_jugadores}}/1
Content-Type: application/json

{
    "nombre": "Paquito",
    "apellido": "Navarro",
    "telefono": 0,
    "posicion": "Drive",
    "nivel": 7,
    "ranking": null,
    "fk_usuario": null,
    "fk_partido": null
}
